-- Preloaded user(s).  Note how we stay well away from the autogenerated ID space.

-- The bootstrap superuser.
insert into serviceuser(id, active, challenge, email, login) values(-1, true, 'headmaster', '', 'headmaster');
insert into userrole(id, rolename, login) values(-1, 'HEADMASTER', 'headmaster');
